//! Drift gate for the binding-surface TSV (`scripts/bindings/surface.tsv`).
//!
//! [`surface.tsv`] is the engine-side export of the radar-enforced MANIFEST
//! in `tests/surface/mod.rs` — one `item<TAB>class<TAB>exposure` line per
//! construct, generated by `scripts/bindings/surface.sh`. Binding repos
//! fetch it from the raw URL at their pinned engine tag and must resolve
//! every line in their `docs/SURFACE.tsv`, so a tagged release carrying a
//! stale TSV would poison every binding gate at once.
//!
//! This test re-derives the TSV from the manifest source with the same
//! line-oriented parse `surface.sh` uses (item = first string literal of
//! each `row(` call, class = the second) and fails on any difference in
//! either direction — a MANIFEST row added without regenerating the TSV, or
//! a hand-edited TSV line that no longer matches the manifest.
//!
//! Regenerate with `scripts/bindings/surface.sh` (never edit by hand).

use std::fs;
use std::path::{Path, PathBuf};

/// `crates/corvid` — the crate under test.
fn manifest_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

/// The manifest source the TSV is generated from.
fn manifest_source() -> PathBuf {
    manifest_dir().join("tests").join("surface").join("mod.rs")
}

/// The committed TSV, at the repo root: `scripts/bindings/surface.tsv`.
fn tsv_path() -> PathBuf {
    manifest_dir()
        .join("..")
        .join("..")
        .join("scripts")
        .join("bindings")
        .join("surface.tsv")
}

/// Extract the first two string literals of every `row(` call inside the
/// `static MANIFEST` block, in order: `(item, class)`. Mirrors the awk state
/// machine in `surface.sh` exactly — the two parsers must agree on both
/// rustfmt shapes (multi-line calls and single-line exempt rows).
fn manifest_rows(source: &str) -> Vec<(String, String)> {
    let mut rows = Vec::new();
    let mut in_manifest = false;
    let mut collecting = false;
    let mut fields: Vec<String> = Vec::new();
    for line in source.lines() {
        if !in_manifest {
            if line.starts_with("static MANIFEST: &[Row] = &[") {
                in_manifest = true;
            }
            continue;
        }
        if line == "];" {
            break;
        }
        let mut rest = line;
        if !collecting {
            let Some(open) = rest.find("row(") else {
                continue;
            };
            collecting = true;
            fields.clear();
            rest = &rest[open + 4..];
        }
        let mut cursor = rest;
        while let Some(open) = cursor.find('"') {
            let Some(rel) = cursor[open + 1..].find('"') else {
                break; // unterminated on this line — manifests never do this
            };
            let lit = &cursor[open + 1..open + 1 + rel];
            cursor = &cursor[open + rel + 2..];
            if fields.len() < 2 {
                fields.push(lit.to_owned());
            }
        }
        if fields.len() == 2 {
            let item = fields[0].clone();
            let class = fields[1].clone();
            rows.push((item, class));
            collecting = false;
        }
    }
    rows
}

#[test]
fn surface_tsv_matches_the_manifest() {
    let source =
        fs::read_to_string(manifest_source()).expect("read tests/surface/mod.rs (run via cargo)");
    let rows = manifest_rows(&source);
    assert!(
        rows.len() > 300,
        "manifest parse imploded ({} rows) — the source format changed",
        rows.len()
    );

    let expected: String = rows
        .iter()
        .map(|(item, class)| format!("{item}\t{class}\tUNMAPPED\n"))
        .collect();
    let actual = match fs::read_to_string(tsv_path()) {
        Ok(text) => text,
        Err(_) => panic!(
            "scripts/bindings/surface.tsv is missing — generate it with \
             scripts/bindings/surface.sh (it is committed and fetched by \
             every binding gate at the pinned engine tag)"
        ),
    };

    assert!(
        Path::new(&tsv_path()).is_file(),
        "surface.tsv path does not resolve: {}",
        tsv_path().display()
    );

    // Compare line-wise for readable failures naming the first drift.
    let expected_lines: Vec<&str> = expected.lines().collect();
    let actual_lines: Vec<&str> = actual.lines().collect();
    for (i, (want, got)) in expected_lines.iter().zip(actual_lines.iter()).enumerate() {
        assert_eq!(
            want,
            got,
            "scripts/bindings/surface.tsv line {} drifted from the MANIFEST — \
             regenerate with scripts/bindings/surface.sh",
            i + 1
        );
    }
    assert_eq!(
        expected_lines.len(),
        actual_lines.len(),
        "scripts/bindings/surface.tsv has {} lines but the MANIFEST has {} — \
         regenerate with scripts/bindings/surface.sh",
        actual_lines.len(),
        expected_lines.len()
    );
}
